# Generated by Django 5.2.4 on 2025-07-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="age",
            field=models.PositiveIntegerField(null=True, verbose_name="Âge"),
        ),
    ]
