# Generated by Django 5.2.4 on 2025-07-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0002_alter_client_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="temp_password",
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(fields=("email",), name="unique_email"),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("account_number",), name="unique_account"
            ),
        ),
    ]
