# Generated by Django 5.2.4 on 2025-07-30 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0003_remove_client_temp_password_client_unique_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="backup_codes",
        ),
        migrations.AddField(
            model_name="client",
            name="chatbot_enabled",
            field=models.BooleanField(default=True, verbose_name="Chatbot activé"),
        ),
        migrations.AddField(
            model_name="client",
            name="preferred_language",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English")],
                default="fr",
                max_length=10,
                verbose_name="Langue préférée",
            ),
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        verbose_name="Numéro de compte bancaire",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Compte Courant"),
                            ("savings", "Compte Épargne"),
                            ("business", "Compte Professionnel"),
                            ("credit", "Compte Crédit"),
                        ],
                        max_length=20,
                        verbose_name="Type de compte",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Solde"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Compte actif"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Compte principal"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte Bancaire",
                "verbose_name_plural": "Comptes Bancaires",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID de session"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Titre de la conversation",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Conversation active"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Chat",
                "verbose_name_plural": "Conversations Chat",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "Utilisateur"),
                            ("bot", "Chatbot"),
                            ("system", "Système"),
                        ],
                        max_length=10,
                        verbose_name="Type de message",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Métadonnées"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "intent_detected",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Intention détectée",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Score de confiance"
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Temps de traitement (ms)"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="authentication.chatconversation",
                        verbose_name="Conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Chat",
                "verbose_name_plural": "Messages Chat",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurringPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_account",
                    models.CharField(max_length=30, verbose_name="Compte destinataire"),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        max_length=100, verbose_name="Nom du destinataire"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                            ("quarterly", "Trimestriel"),
                            ("yearly", "Annuel"),
                        ],
                        max_length=15,
                        verbose_name="Fréquence",
                    ),
                ),
                (
                    "next_payment_date",
                    models.DateTimeField(verbose_name="Prochaine date de paiement"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_payments",
                        to="authentication.bankaccount",
                        verbose_name="Compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Récurrent",
                "verbose_name_plural": "Paiements Récurrents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("debit", "Débit"),
                            ("credit", "Crédit"),
                            ("transfer", "Virement"),
                            ("payment", "Paiement"),
                            ("withdrawal", "Retrait"),
                            ("deposit", "Dépôt"),
                        ],
                        max_length=15,
                        verbose_name="Type de transaction",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "recipient_account",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Compte destinataire",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nom du destinataire",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Référence"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de traitement"
                    ),
                ),
                (
                    "initiated_by_chatbot",
                    models.BooleanField(
                        default=False, verbose_name="Initié par chatbot"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="authentication.bankaccount",
                        verbose_name="Compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
