# Generated by Django 5.2.4 on 2025-08-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_remove_client_backup_codes_client_chatbot_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="account_number",
            field=models.CharField(
                default="sdMCpBVEsJ",
                max_length=20,
                unique=True,
                verbose_name="Numéro de compte",
            ),
        ),
    ]
