# Generated by Django 5.2.4 on 2025-08-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_alter_client_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="account_number",
            field=models.CharField(
                default="9XP7wuFPl9",
                max_length=20,
                unique=True,
                verbose_name="Numéro de compte",
            ),
        ),
    ]
